/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class ArrayLoopTest {
    @Test public void testRoll() {
      int numberRolls = 5;
      int[] diceRoll = ArrayLoops.roll(numberRolls);
      assertEquals(5, numberRolls);
      for(int dice: diceRoll) {
          assertTrue("dice rolls from 1 to 6", dice >= 1 && dice <= 6);
      }
    }

    @Test public void testContainsDuplicates() {
        int[] noDup = {1, 2, 3, 4, 5, 6};
        int[] hasDup = {1, 2, 3, 4, 5, 6};
        int[] emptyArr = {};

        assertFalse("Returns false when there are no duplicates",
                ArrayLoops.containsDuplicates(noDup));

        assertTrue("Returns false when there are no duplicates",
                ArrayLoops.containsDuplicates(hasDup));

        assertFalse("Returns false when its empty",
                ArrayLoops.containsDuplicates(emptyArr));


    }

    @Test public void testGetAverage() {
      double number = 1e-10;

      int[] input1 ={10};
      int[] input2 = {1, 2, 3};
      int[] input3 = {-2, 2, 5, 5};
      int[] emptyArr = {};

      assertEquals("average of single average", ArrayLoops.getAverage(input1), 10.0, number);
      assertEquals("average of multiple averages", ArrayLoops.getAverage(input2),2.0 , number);
      assertEquals("average even with a negative number", ArrayLoops.getAverage(input3), 2.5, number);


    }

    @Test public void testAverageOfAverage() {
        int[][] input = {
                {1},
                {3},
                {5}
        };

        int [][] input2 = {
                {0,20,40},
                {12,24},
                {20}

        };

        assertEquals("Array of averages", ArrayLoops.averageOfAverage(input), 2.0 );
    }
}
