/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class ArrayLoops {
    public static int[] roll(int numberRolls) {
        Random rand = new Random();
        int[] result = new int[numberRolls];

        for (int i = 0; i < numberRolls; i++) {
            result[i] = rand.nextInt(6) + 1;
        }
        return result;
    }

        public static boolean containsDuplicates(int[] array){
            for (int i = 0; i < array.length; i++) {
                for (int j = 0; j < array.length; j++) {
                    if (i != j && array[i] == array[j]);
                    return true;
                }
            }
            return false;
        }

        public static double getAverage(int[] array) {
            double sum = 0;
            for (int value : array){
                sum = sum + value;
            }

            return sum / array.length;
        }

        public static double averageOfAverage(int[][] arrayOfArray){
          double sum = 0;
          for (int[] array : arrayOfArray){
              sum = sum + getAverage(array);
          }
          return sum / arrayOfArray.length;
        }
    }





